version: '3.4'

# Defaults

x-build-args-36: &build_args_36
  IMAGE_TAG: "3.6-buster"

x-build-args-37: &build_args_37
  IMAGE_TAG: "3.7-buster"

x-build-args-38: &build_args_38
  IMAGE_TAG: "3.8-buster"

services:

  # Devbox
  
  dev: &dev
    build: &default_build
      dockerfile: ./docker/Dockerfile
      context: .
    image: little-cheesemonger-dev
    command: /bin/bash
    volumes:
      - ./:/app

  # Test & Lint suite
  
  test-36:
    <<: *dev
    build:
      <<: *default_build
      args:
        <<: *build_args_36
    image: little-cheesemonger-test-36
    command: docker/run_tests.sh
  
  test-37:
    <<: *dev
    build:
      <<: *default_build
      args:
        <<: *build_args_37
    image: little-cheesemonger-test-37
    command: docker/run_tests.sh
  
  test-38:
    <<: *dev
    build:
      <<: *default_build
      args:
        <<: *build_args_38
    image: little-cheesemonger-test-38
    command: docker/run_tests.sh --format-code
